\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2020_07_08_creature_template_npcbot_extras.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2020_09_25_creature_template.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2020_10_14_creature_classlevelstats.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2020_10_14_creature_template.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2020_10_15_creature_template.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2020_11_07_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2020_12_11_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2021_01_04_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2021_01_05_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2021_01_08_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2021_02_01_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2021_03_29_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2021_08_20_creature_template_npcbot_extras.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2021_08_27_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2021_10_12_creature_template.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_01_02_00_creature_template_npcbot_extras.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_01_02_01_generate_equips_necromancer.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_01_02_02_creature_template.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_01_02_03_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_01_31_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_06_15_00_creature_template_npcbot_extras.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_06_17_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_06_22_00_creature_template_npcbot_extras.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_06_22_01_generate_equips_sea_witch.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_06_22_02_creature_template.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_06_22_03_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_06_23_00_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_06_24_00_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_06_24_01_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_06_24_02_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_07_04_00_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_07_25_00_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_11_15_00_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_11_30_00_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_12_08_00_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_12_17_00_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_12_17_01_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2022_12_23_00_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_01_02_00_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_01_10_00_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_01_11_00_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_03_10_00_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_03_10_01_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_03_12_00_creature_template_npcbot_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_03_14_00_creature_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_03_21_00_creature_template_npcbot_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_04_04_00_creature_template_npcbot_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_04_11_00_creature_template_npcbot_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_04_16_00_creature_template_npcbot_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_04_18_00_creature_template_npcbot_appearance.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_04_22_00_creature_template_npcbot_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_04_28_00_creature_template.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_05_14_00_creature_template_npcbot_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_05_16_00_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_05_20_00_creature_template.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_05_20_01_creature_equip_template.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_05_20_02_creature_template_npcbot_extras.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_05_20_03_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_06_02_00_creature_template_npcbot_extras.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_06_03_00_creature_template.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_06_09_00_creature_template_npcbot_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_06_16_00_creature_template_npcbot_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_06_18_00_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_06_18_01_creature_template_npcbot_disabled_items.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_06_19_00_creature_template_npcbot_disabled_items.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_06_19_01_creature_template.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_06_22_00_command.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_06_24_00_creature_template_npcbot_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_06_26_00_creature_template_npcbot_wander_nodes.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_07_01_00_creature_template_npcbot_disabled_items.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2023_08_13_00_creature_template_npcbot_appearance.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2024_03_12_00_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2024_03_18_00_npc_text.sql 
\. D:\games\wowserver\TrinityCoreTogether\sql\Bots\updates\world\2024_03_19_00_npc_text.sql 
